export const categorySkills: Record<string, string[]> = {
  'plumbing': ['Pipe Installation & Repair', 'Drainage & Sewer Systems', 'Water Heater Maintenance', 'Fixture Installation (Faucets, Sinks, Toilets)', 'Leak Detection & Repair'],
  'electrical-work': ['Wiring & Rewiring', 'Circuit Breaker & Panel Installation', 'Lighting Installation & Repair', 'Electrical Safety Inspection', 'Smart Home Wiring'],
  'ac-hvac-services': ['AC Installation & Repair', 'AC Maintenance & Servicing', 'Duct Cleaning & Repair', 'Heating System Repair', 'Thermostat Installation'],
  'home-cleaning': ['General House Cleaning', 'Deep Cleaning', 'Move-In / Move-Out Cleaning', 'Carpet & Upholstery Cleaning', 'Window & Glass Cleaning'],
  'painting-decorating': ['Interior Wall Painting', 'Exterior Painting', 'Wallpaper Installation & Removal', 'Texture & Finish Coating', 'Furniture Refinishing'],
  'carpentry-furniture': ['Custom Furniture Making', 'Cabinet Installation & Repair', 'Door & Window Repair', 'Wood Polishing & Finishing', 'Deck & Pergola Construction'],
  'gardening-landscaping': ['Lawn Mowing & Trimming', 'Tree Trimming & Removal', 'Garden Design & Planting', 'Irrigation System Installation', 'Weed Control & Fertilization'],
  'pest-control': ['Insect Control (Cockroaches, Ants, Spiders)', 'Rodent Control', 'Termite Treatment & Prevention', 'Mosquito Control', 'Fumigation Services'],
  'home-repair-maintenance': ['Drywall Repair & Installation', 'Tile & Grout Repair', 'Caulking & Weatherproofing', 'Door & Hinge Repair', 'General Handyman Services'],
  'moving-packing': ['Local Residential Moving', 'Packing & Unpacking', 'Furniture Disassembly & Assembly', 'Loading & Unloading', 'Piano & Heavy Item Moving'],
  'flooring-tiling': ['Tile Installation (Ceramic/Porcelain)', 'Hardwood Flooring Installation', 'Laminate & Vinyl Flooring', 'Carpet Installation', 'Grout Cleaning & Sealing'],
  'vehicle-services': ['Car Wash & Detailing', 'Oil Change & Fluid Check', 'Tire Rotation & Replacement', 'Brake Pad Replacement', 'Battery Replacement & Testing'],
  'roofing-gutters': ['Roof Repair & Leak Fix', 'Gutter Cleaning & Repair', 'Roof Replacement (Shingles/Metal)', 'Skylight Installation'],
  'locksmith-services': ['Lock Installation & Repair', 'Key Duplication & Programming', 'Emergency Lockout Service', 'Smart Lock Installation', 'Safe Opening & Repair'],
  'appliance-repair': ['Refrigerator & Freezer Repair', 'Washing Machine & Dryer Repair', 'Oven & Stove Repair', 'Dishwasher Repair', 'Microwave & Small Appliance Repair'],
  'concrete-masonry': ['Driveway & Walkway Paving', 'Brick & Block Laying', 'Retaining Wall Construction', 'Concrete Slab & Foundation', 'Stucco & Plaster Work'],
  'pool-maintenance': ['Pool Cleaning & Skimming', 'Chemical Balancing & Treatment', 'Pump & Filter Repair', 'Pool Tile & Surface Cleaning', 'Pool Cover Installation'],
  'waterproofing': ['Roof Waterproofing', 'Basement Waterproofing', 'Bathroom & Kitchen Waterproofing', 'Terrace & Balcony Coating', 'Crack Injection & Sealant'],
  'glass-mirror-work': ['Window Glass Replacement', 'Mirror Installation & Cutting', 'Shower Screen Installation', 'Glass Table Top & Shelving', 'Storefront Glass Repair'],
  'welding-metal-fabrication': ['Arc & MIG Welding', 'Gate & Railing Fabrication', 'Metal Structure Repair', 'Custom Metal Furniture'],
  'web-development': ['Frontend Development (React/Next.js)', 'Backend Development (Node.js/Python)', 'Full Stack Development', 'WordPress & CMS Development', 'E-commerce Development (Shopify/WooCommerce)'],
  'mobile-app-development': ['iOS Development (Swift)', 'Android Development (Kotlin)', 'Cross-Platform (React Native/Flutter)', 'App UI/UX Design'],
  'graphic-design': ['Logo & Brand Identity Design', 'Social Media Graphics', 'Print Design (Flyers, Brochures, Business Cards)', 'Photo Editing & Retouching', 'Packaging & Label Design'],
  'digital-marketing': ['Search Engine Optimization (SEO)', 'Social Media Advertising (Facebook/Instagram/TikTok)', 'Google Ads & PPC Campaigns', 'Email Marketing (Mailchimp/Klaviyo)', 'Content Marketing Strategy'],
  'writing-translation': ['Content Writing & Blogging', 'Copywriting', 'Translation (Multi-Language)', 'Technical Writing', 'Proofreading & Editing'],
  'data-entry-virtual-assistance': ['Data Entry & Database Cleanup', 'Virtual Administrative Support', 'Email & Calendar Management', 'CRM Data Management (HubSpot/Salesforce)', 'Research & Lead Generation'],
  'social-media-management': ['Content Creation & Scheduling', 'Community Management & Engagement', 'Analytics & Performance Reporting', 'Influencer Outreach', 'Brand Voice & Strategy'],
  'video-editing-animation': ['Video Editing (Adobe Premiere/Final Cut)', 'Motion Graphics & Titles', '2D Animation (After Effects)', '3D Animation (Blender/Maya)', 'VFX & Compositing'],
  'photography': ['Portrait Photography', 'Event Photography (Weddings, Parties)', 'Product Photography', 'Real Estate Photography', 'Photo Retouching & Restoration'],
  'ui-ux-design': ['Wireframing & Prototyping (Figma/Sketch)', 'User Research & Testing', 'Interaction Design', 'Design System Creation'],
  'cloud-devops': ['AWS / GCP / Azure Setup & Management', 'CI/CD Pipeline Setup', 'Docker & Kubernetes', 'Infrastructure as Code (Terraform)', 'Monitoring & Logging (Datadog/Grafana)'],
  'cybersecurity': ['Penetration Testing', 'Vulnerability Assessment', 'Security Audit & Compliance', 'Firewall & Network Security Setup'],
  'database-administration': ['SQL Query Optimization', 'Database Migration & Backup', 'NoSQL Setup (MongoDB/DynamoDB)', 'Database Performance Tuning'],
  'data-science-machine-learning': ['Data Analysis & Visualization (Python/R)', 'Machine Learning Model Training', 'Natural Language Processing (NLP)', 'Computer Vision', 'AI Chatbot Development'],
  'game-development': ['Unity Game Development', 'Unreal Engine Development', '2D Game Art & Pixel Art', 'Game Testing & QA'],
  'technical-support-it': ['IT Helpdesk & Remote Support', 'Network Setup (Router/Switch/Wi-Fi)', 'Software Installation & Troubleshooting', 'Computer Repair & Upgrades', 'Printer & Peripheral Setup'],
  'voice-over-audio-production': ['Voice Recording & Narration', 'Audio Editing & Mixing', 'Podcast Production', 'Sound Design & Foley', 'Music Production & Beat Making'],
  'crm-marketing-automation': ['HubSpot Setup & Management', 'Salesforce Administration', 'Workflow Automation (Zapier/Make)', 'Lead Scoring & Nurture Campaigns'],
  'e-commerce-management': ['Shopify Store Setup & Customization', 'Product Listing & Optimization', 'Amazon FBA & Seller Central', 'Conversion Rate Optimization (CRO)', 'Inventory & Order Management'],
  'ar-vr-3d-modeling': ['3D Modeling (Blender/3ds Max)', 'VR Application Development', 'AR Filters & Effects', '3D Product Visualization', 'Virtual Tour Creation'],
  'parcel-document-delivery': ['Document Courier', 'Parcel Delivery', 'Same-City Drop-off', 'Cross-City Pickup & Drop', 'Post Office / Courier Errands'],
  'personal-errands': ['Errand Runner', 'Station / Bus-Stand Pickup & Drop', 'Shopping Assistant', 'Government Office Errands', 'Queue & Booking Assistance'],
  'grocery-shopping-delivery': ['Grocery Shopping & Delivery', 'Pharmacy / Medicine Pickup', 'Shop & Deliver', 'Market / Bazaar Runs'],
  'move-carry-light': ['Furniture Carry & Setup', 'Market Shopping Carry', 'Bulk Parcel Moving', 'Shift Help (Loading & Unloading)'],
};
